#    snapcraft yaml for py-sol-fc.
#    Copyright (C) 2022-2025 joker2770
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# After registering a name on build.snapcraft.io, commit an uncommented line:
name: py-sol-fc
version: '3.2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: PySolFC is an extended version of PySol. # 79 char long summary
description: |
  PySolFC (PySol Fan Club edition) is an extended version of PySol (a solitaire card games collection).

  _more build details: https://github.com/Joker2770/PySolFC-snap_

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core20
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

layout:
  /usr/share/tcltk:
    bind: $SNAP/usr/share/tcltk
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  
apps:
  py-sol-fc:
    command-chain: ["snap/command-chain/alsa-launch"]
    command: "bin/python3 $SNAP/usr/share/games/pysol.py"
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - audio-playback
      - pulseaudio
      - alsa
      - removable-media
      - network
      - network-bind

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad

  # Launcher for fixing the Glibc locales
  # https://forum.snapcraft.io/t/the-locales-launch-launcher-fix-glibc-locales-in-the-snap-runtime/10296
  locales-launch:
    after: [alsa-mixin]
    source: https://github.com/brlin-tw/locales-launch.git
    source-tag: v1.0.0
    plugin: dump
    stage-packages:
      # For localedef(1)
      - libc-bin

      # For locale data used by localedef(1)
      - locales

      # All pre-generated locale data
      # DISABLED: Lots of duplicate data will be included in the snap when this is staged unless
      # the target machine has no resource to generate them in runtime otherwise not use it
      #
      #   Lack of compiled locales breaks gettext based localization - snapcraft - snapcraft.io
      #   https://forum.snapcraft.io/t/lack-of-compiled-locales-breaks-gettext-based-localisation/3758
      #
      #- locales-all

    stage:
      - bin/locales-launch
      - etc/locale.alias
      - usr/bin/localedef
      - usr/share/doc/locales
      - usr/share/i18n
      - usr/share/locale

  env:
    after: [locales-launch]
    plugin: python
    python-packages:
      - pygame
      - configobj
      - pycotap
      - attrs
      - pysol_cards
    stage-packages:
      - libpulse0
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libxss1
      - libxxf86vm1
      - tk8.6
      - tcl8.6
      - python3-tk
    build-packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libfreetype6-dev
      - libportmidi-dev
      - libjpeg62-dev
      - tk8.6-dev
      - tcl8.6-dev
      - python3-setuptools

  py-sol-fc:
    after: [env]
    plugin: dump
    source: "https://cyfuture.dl.sourceforge.net/project/pysolfc/PySolFC/PySolFC-3.2.0/PySolFC-3.2.0.tar.xz?viasf=1"
    source-type: tar
    organize:
      '*': usr/share/games/
    prime:
      - -Makefile
      - -android
      - -tests

  cardsets:
    after: [py-sol-fc]
    plugin: dump
    source: "https://github.com/shlomif/PySolFC-Cardsets.git"
    source-depth: 1
    source-branch: master
    source-type: git
    organize:
      '*': usr/share/games/data/

  music:
    after: [cardsets]
    plugin: dump
    source: "https://github.com/shlomif/pysol-music.git"
    source-depth: 1
    source-branch: master
    source-type: git
    organize:
      'data/music/*': usr/share/games/data/music/
      'COPYING': usr/share/games/data/music/
    prime:
      - -README*
      - -Makefile
      - -NEWS
