#    snapcraft yaml for py-sol-fc.
#    Copyright (C) 2021-2022 joker2770
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# After registering a name on build.snapcraft.io, commit an uncommented line:
name: py-sol-fc
version: '2.16.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: PySolFC is an extended version of PySol. # 79 char long summary
description: |
  PySolFC (PySol Fan Club edition) is an extended version of PySol (a solitaire card games collection).

  _more build details: https://github.com/Joker2770/PySolFC-snap_

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

layout:
  /usr/share/tcltk:
    bind: $SNAP/usr/share/tcltk
  
apps:
  py-sol-fc:
    command: usr/share/games/launcher.sh
    extensions: [gnome-3-28]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - gsettings
      - wayland
      - unity7
      - x11
      - opengl
      - audio-playback
      - removable-media
      - network
      - network-bind

parts:
  env:
    plugin: python
    python-version: python3
    python-packages:
      - pygame
      - configobj
      - pycotap
      - attrs
    stage-packages:
      - libpulse0
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libxss1
      - libxxf86vm1
      - tk8.6
      - tcl8.6
      - python3-tk
    build-packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libfreetype6-dev
      - libportmidi-dev
      - libjpeg8-dev
      - tk8.6-dev
      - tcl8.6-dev
      - python3-setuptools

  py-sol-fc:
    after: [env]
    plugin: dump
    source: "https://github.com/Joker2770/PySolFC-snap/raw/main/PySolFC-2.16.0.tar.xz"
    source-type: tar
    organize:
      '*': usr/share/games/
    prime:
      - -Makefile

  cardsets:
    after: [py-sol-fc]
    plugin: dump
    source: "https://github.com/Joker2770/PySolFC-snap/raw/main/PySolFC-Cardsets-2.1.tar.bz2"
    source-type: tar
    organize:
      '*': usr/share/games/data/

  launcher:
    after: [cardsets]
    plugin: dump
    source: "https://github.com/Joker2770/PySolFC-snap.git"
    source-depth: 1
    source-branch: main
    source-type: git
    organize:
      launcher.sh: usr/share/games/
    prime:
      - -PySolFC-*
      - -README*
      - -LICENSE
      - -snap
    override-build: |
      snapcraftctl build
      chmod +x launcher.sh
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/games/
